[env]
_.python.venv = { path = '.venv', create = true }

[tools]
python = "3.12"
duckdb = "1"

[plugins]
duckdb = 'https://github.com/asdf-community/asdf-duckdb'


[tasks.defult]
run  = ['pip install -r requirements.txt']

