# curl https://mise.run | sh
# echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
# echo 'eval "$(~/.local/bin/mise activate zsh)"' >> ~/.zshrc

[env]
_.python.venv = { path = '.venv', create = true }

[tools]
python = "3.12"
duckdb = "1"

[plugins]
duckdb = 'https://github.com/asdf-community/asdf-duckdb'


[tasks.default]
run  = ['pip install -r requirements.txt']

